demo:
   resource: "@DemoBundle/Controller/DefaultController.php"
   type:     rest
app:
    resource: '@AppBundle/Controller/'
    type: annotation

nelmio-api-doc:
   resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
   prefix:   /documentation